### 函数调用栈中抛出的异常是责任链模式的体现

函数体内部抛出异常后，如果当前函数不捕获该异常，将异常抛出，则需要调用当前函数的函数来捕获或抛出异常，如此下去，直到异常被捕获。
